/* Original, simplified tasting-note vocabulary for everyday discovery. */
window.CoffeeFlavors = [
  ['floral','Jasmine','Airy white-flower fragrance with a delicate, tea-like finish.','Soft · fragrant','flower','#eee8cc'],
  ['floral','Rose','A sweet petal aroma, like rosewater, with a gently perfumed finish.','Petal-like · perfumed','rose','#ce8e9c'],
  ['floral','Hibiscus','A fragrant, tart impression reminiscent of ruby-red flower tea.','Tart · fragrant','flower','#bd5872'],
  ['floral','Orange blossom','Fresh white flowers with a sweet, softly citrus-scented aroma.','Sweet · fragrant','flower','#f0ce85'],
  ['floral','Lavender','A gently herbal floral scent with a distinctive, lingering perfume.','Herbal · floral','sprig','#9b88b1'],
  ['floral','Chamomile','Soft dried-flower fragrance with an apple-like, mellow sweetness.','Mellow · floral','daisy','#e3bd61'],
  ['floral','Elderflower','A light blossom aroma that can feel fresh, delicate, and slightly fruity.','Light · fresh','cluster','#ddd4a0'],
  ['floral','Honeysuckle','A nectar-like floral impression with a rounded, honeyed aroma.','Nectar-like · soft','flower','#e2bc75'],
  ['floral','Black tea','Fragrant dried tea leaves with a brisk, gently drying finish.','Brisk · tea-like','tea','#8c6953'],
  ['floral','Green tea','A fresh leaf aroma with a delicate, softly herbal character.','Fresh · leafy','tea','#879c62'],
  ['fruity','Strawberry','A red-fruit impression that recalls ripe strawberries and a little jam.','Red fruit · juicy','strawberry','#cb737c'],
  ['fruity','Blueberry','Rounded dark-berry sweetness with a soft, juicy aroma.','Dark berry · round','berries','#7e86aa'],
  ['fruity','Raspberry','Bright red-berry fragrance with a tangy, delicate finish.','Red berry · tangy','raspberry','#bd637a'],
  ['fruity','Blackberry','Deep berry flavor with a sweet-tart, slightly brambly impression.','Dark berry · rich','raspberry','#75647e'],
  ['fruity','Cherry','A juicy red-fruit note that can recall fresh cherries or cherry jam.','Juicy · round','cherry','#b95f67'],
  ['fruity','Peach','Soft stone-fruit sweetness with a fragrant, ripe-peach impression.','Stone fruit · soft','stone','#e8ac8d'],
  ['fruity','Apricot','A golden stone-fruit aroma, gently tangy and sometimes dried-fruit-like.','Golden fruit · tangy','stone','#dca268'],
  ['fruity','Plum','Rounded purple-fruit flavor with a deeper, sweet-tart finish.','Stone fruit · deep','stone','#93738c'],
  ['fruity','Grape','A juicy, grape-like impression with a lively, rounded sweetness.','Juicy · rounded','grapes','#9581a9'],
  ['fruity','Apple','A crisp orchard-fruit note, from fresh green apple to mellow cooked apple.','Orchard fruit · crisp','apple','#b5bb75'],
  ['citrus','Lemon','A lively, tart citrus impression with a clean, zest-like aroma.','Zesty · bright','lemon','#e6cc72'],
  ['citrus','Lime','Sharp, fresh citrus with a fragrant green-zest character.','Green citrus · lively','citrus','#a2b871'],
  ['citrus','Orange','Rounded citrus sweetness, recalling fresh orange flesh and peel.','Juicy · sweet citrus','citrus','#e5ad70'],
  ['citrus','Grapefruit','A bright, tangy citrus note with a pleasantly pithy edge.','Tangy · pithy','citrus','#d58d88'],
  ['citrus','Mandarin','Soft, sweet citrus with a fragrant peel and mellow acidity impression.','Sweet citrus · gentle','citrus','#e1a068'],
  ['citrus','Tangerine','A vivid orange-citrus note with a juicy, sweet-tart character.','Orange citrus · vivid','citrus','#d89158'],
  ['citrus','Bergamot','A fragrant citrus-peel aroma, reminiscent of the scent of Earl Grey tea.','Aromatic · zesty','citrus','#bec180'],
  ['citrus','Pomelo','A mellow citrus impression with soft sweetness and a little peel-like bitterness.','Mellow citrus · pithy','citrus','#d4ca93'],
  ['citrus','Yuzu','A fragrant, tart citrus impression somewhere between lemon and mandarin.','Fragrant · tart','citrus','#d6bd68'],
  ['citrus','Kumquat','Sweet citrus peel paired with a bright, tart-fruit impression.','Peel-like · sweet-tart','lemon','#dca065'],
  ['sweet','Honey','A rounded, nectar-like sweetness with a softly floral aroma.','Nectar-like · golden','honey','#d0a05b'],
  ['sweet','Caramel','A warm cooked-sugar impression, sweet and gently buttery.','Cooked sugar · round','cubes','#bd8d62'],
  ['sweet','Toffee','A rich browned-sugar impression with a buttery, lingering finish.','Buttery · rich','cubes','#ab7852'],
  ['sweet','Brown sugar','A familiar warm sugar note with a hint of molasses depth.','Warm sugar · mellow','sugar','#bc9973'],
  ['sweet','Maple syrup','A deep golden sweetness with a gently woody, syrup-like aroma.','Golden · syrupy','maple','#b78654'],
  ['sweet','Vanilla','A soft, sweet-smelling vanilla-pod impression with a creamy character.','Soft · creamy aroma','vanilla','#9e795e'],
  ['sweet','Molasses','A dark, rich cooked-sugar note with a slightly bittersweet depth.','Dark sugar · deep','honey','#816049'],
  ['sweet','Marzipan','A sweet almond-paste impression that combines nutty aroma and soft sweetness.','Almond-like · sweet','cubes','#d8c69f'],
  ['sweet','Nougat','A soft confection-like note, recalling honeyed sweetness and toasted nuts.','Honeyed · nutty','nougat','#d8c7a7'],
  ['sweet','Date','A dense dried-fruit sweetness with warm, caramel-like depth.','Dried fruit · rich','date','#a47b5b'],
  ['nutty','Almond','A mild, softly sweet nut aroma with a rounded toasted character.','Mild nut · soft','almond','#bf9871'],
  ['nutty','Hazelnut','A fragrant toasted-nut impression with a sweet, rounded finish.','Toasted nut · round','hazelnut','#b08a62'],
  ['nutty','Walnut','A deeper nut flavor with an earthy, lightly drying impression.','Deep nut · earthy','walnut','#a18a6c'],
  ['nutty','Peanut','A familiar roasted-nut aroma with a savory, rounded character.','Roasted nut · savory','peanut','#c4a778'],
  ['nutty','Cashew','A gentle nutty impression with a soft, buttery character.','Buttery nut · gentle','cashew','#d1b88b'],
  ['nutty','Pecan','A rich toasted-nut note with a warm, almost caramel-like sweetness.','Toasted nut · rich','almond','#a4825c'],
  ['nutty','Cocoa','A dry cocoa-powder impression with a balanced, bittersweet aroma.','Cocoa powder · dry','cocoa','#9c775c'],
  ['nutty','Milk chocolate','A soft chocolate impression with creamy, mellow sweetness.','Creamy cocoa · mellow','chocolate','#ae876e'],
  ['nutty','Dark chocolate','A rich cocoa impression with deeper bittersweet intensity.','Bittersweet cocoa · deep','chocolate','#765c50'],
  ['nutty','Cacao nibs','An earthy cocoa impression with a roasted, slightly nutty edge.','Roasted cocoa · earthy','nibs','#8f6c55'],
  ['spiced','Cinnamon','A warm, fragrant wood-spice aroma with a gently sweet impression.','Warm spice · sweet','cinnamon','#b18b65'],
  ['spiced','Clove','A deep, aromatic spice note with a pungent, lingering character.','Aromatic spice · deep','clove','#92785e'],
  ['spiced','Nutmeg','A mellow, woody spice impression with warm, nut-like depth.','Warm spice · woody','nutmeg','#ac8c65'],
  ['spiced','Cardamom','A fragrant spice aroma with a fresh, almost citrus-like lift.','Fragrant spice · fresh','cardamom','#a4ad78'],
  ['spiced','Ginger','A fresh, warming spice impression with a lively aromatic edge.','Fresh spice · lively','ginger','#ccae7b'],
  ['spiced','Allspice','A rounded spice impression that recalls clove, cinnamon, and nutmeg.','Rounded spice · warm','pepper','#a28a68'],
  ['spiced','Black pepper','A dry, pungent spice aroma with a distinctly peppery finish.','Dry spice · pungent','pepper','#7d786b'],
  ['spiced','Cedar','A dry, fragrant wood impression, like fresh cedar shavings.','Dry wood · fragrant','cedar','#8b9a78'],
  ['spiced','Tobacco','A dried-leaf aroma with earthy, gently sweet depth; a tasting comparison.','Dried leaf · earthy','leaf','#b0956e'],
  ['spiced','Licorice','A dark, sweet-spice aroma with an anise-like, lingering character.','Sweet spice · lingering','licorice','#786758']
].map(([family,name,description,character,art,color])=>({id:name.toLowerCase().replaceAll(' ','-'),family,name,description,character,art,color,image:`assets/flavors/${name.toLowerCase().replaceAll(' ','-')}.svg`}));
